DB2UTILC.PGM: DB2UTILC.PGM.CLLE
QSHBASHC.PGM: QSHBASHC.PGM.CLLE QSHEXEC.CMD QSHEXECC.PGM
QSHCALLC.PGM: QSHCALLC.PGM.CLLE QSHGETPARM.CMD QSHGETPARR.PGM
QSHCALLT.PGM: QSHCALLT.PGM.CLLE QSHCALL.CMD
QSHCPYSRCC.PGM: QSHCPYSRCC.PGM.CLLE
QSHCRTWTMC.PGM: QSHCRTWTMC.PGM.CLLE QSHQRYTMP.CMD
QSHEXECC.PGM: QSHEXECC.PGM.CLLE
QSHEXECSCC.PGM: QSHEXECSCC.PGM.CLLE
QSHIFSCHKC.PGM: QSHIFSCHKC.PGM.CLLE
QSHLOGSCAC.PGM: QSHLOGSCAC.PGM.CLLE
QSHPATHC.PGM: QSHPATHC.PGM.CLLE
QSHPHPRUNC.PGM: QSHPHPRUNC.PGM.CLLE PHPPATH.DTAARA
QSHPORTCHC.PGM: QSHPORTCHC.PGM.CLLE QSHQRYTMP.CMD
QSHPORTENC.PGM: QSHPORTENC.ILEPGM QSHCRTWTMP.CMD
QSHPYCALLC.PGM: QSHPYCALLC.PGM.CLLE QSHGETPARM.CMD PYPATH.DTAARA
QSHPYCALLT.PGM: QSHPYCALLT.PGM.CLLE QSHPYCALL.CMD
QSHPYRUNC.PGM: QSHPYRUNC.PGM.CLLE
QSHQRYTMPC.PGM: QSHQRYTMPC.PGM.CLLE
QSHSETPROC.PGM: QSHSETPROC.PGM.CLLE
QSHSRCIFSC.PGM: QSHSRCIFSC.PGM.CLLE
SRCBLDC.PGM: SRCBLDC.PGM.CLLE





