DB2UTIL.CMD: DB2UTIL.CMDSRC
DB2UTIL.CMD: PGM = DB2UTILC
DB2UTIL.CMD: PRDLIB = $objlib
DB2UTIL.CMD: TEXT = Execute db2util Query to IFS Output File via bash

QSHBASH.CMD: QSHBASH.CMDSRC
QSHBASH.CMD: PGM = QSHBASHC
QSHBASH.CMD: TEXT = Run Bash Command via Qshell

QSHCALL.CMD: QSHCALL.CMDSRC
QSHCALL.CMD: PGM = QSHCALLC
QSHCALL.CMD: ALLOW = *IPGM *BPGM *IMOD *BMOD
QSHCALL.CMD: TEXT = Run QShell Command Line and Return Parms

QSHCPYSRC.CMD: QSHCPYSRC.CMDSRC
QSHCPYSRC.CMD: PGM = QSHCPYSRCC
QSHCPYSRC.CMD: ALLOW = *IPGM *BPGM *IMOD *BMOD
QSHCPYSRC.CMD: TEXT = Copy Source Member to IFS File

QSHCRTWTMP.CMD: QSHCRTWTMP.CMDSRC
QSHCRTWTMP.CMD: PGM = QSHCRTWTMC
QSHCRTWTMP.CMD: TEXT = Create Program with QTEMP File

QSHCURL.CMD: QSHCURL.CMDSRC
QSHCURL.CMD: PGM = QSHCURLC
QSHCURL.CMD: TEXT = Run Curl Command via QShell

QSHEXEC.CMD: QSHEXEC.CMDSRC
QSHEXEC.CMD: PGM = QSHEXECC
QSHEXEC.CMD: TEXT = Run QShell Command Line

QSHEXECSRC.CMD: QSHEXECSRC.CMDSRC
QSHEXECSRC.CMD: PGM = QSHEXECSCC
QSHEXECSRC.CMD: TEXT = Run QShell .sh script from Source File Member

QSHGETPARM.CMD: QSHGETPARM.CMDSRC
QSHGETPARM.CMD: PGM = QSHGETPARR
QSHGETPARM.CMD: ALLOW = *IPGM *BPGM *IMOD *BMOD
QSHGETPARM.CMD: TEXT = Scan Qshell Log File for Parameter Values

QSHIFSCHK.CMD: QSHIFSCHK.CMDSRC
QSHIFSCHK.CMD: PGM = QSHIFSCHKC
QSHIFSCHK.CMD: TEXT = Check for IFS File Existence

QSHLOGSCAN.CMD: QSHLOGSCAN.CMDSRC
QSHLOGSCAN.CMD: PGM = QSHLOGSCAC
QSHLOGSCAN.CMD: TEXT = Scan Qshell Log File for Value

QSHPATH.CMD: QSHPATH.CMDSRC
QSHPATH.CMD: PGM = QSHPATHC
QSHPATH.CMD: TEXT = Set Open Source Package Path Environment Variables

QSHPHPRUN.CMD: QSHPHPRUN.CMDSRC
QSHPHPRUN.CMD: PGM = QSHPHPRUNC
QSHPHPRUN.CMD: TEXT = Run PHP Script via QShell

QSHPORTCHK.CMD: QSHPORTCHK.CMDSRC
QSHPORTCHK.CMD: PGM = QSHPORTCHC
QSHPORTCHK.CMD: TEXT = Check for active TCP/IP Local Port

QSHPORTEND.CMD: QSHPORTEND.CMDSRC
QSHPORTEND.CMD: PGM = QSHPORTENC
QSHPORTEND.CMD: TEXT = End All Jobs for Active TCP/IP Local Port

QSHPYCALL.CMD: QSHPYCALL.CMDSRC
QSHPYCALL.CMD: PGM = QSHPYCALLC
QSHPYCALL.CMD: ALLOW = *IPGM *BPGM *IMOD *BMOD
QSHPYCALL.CMD: TEXT = Run Python Script via Qshell and Return Parms

QSHPYRUN.CMD: QSHPYRUN.CMDSRC
QSHPYRUN.CMD: PGM = QSHPYRUNC
QSHPYRUN.CMD: TEXT = Run Python Script via Qshell

QSHQRYTMP.CMD: QSHQRYTMP.CMDSRC
QSHQRYTMP.CMD: PGM = QSHQRYTMPC
QSHQRYTMP.CMD: TEXT = SQL Query Data to Selected Temp Table with RUNSQL

QSHSETPROF.CMD: QSHSETPROF.CMDSRC
QSHSETPROF.CMD: PGM = QSHSETPROC
QSHSETPROF.CMD: TEXT = Set up .profile, .bash_profile and .bashrc files

QSHSRCIFS.CMD: QSHSRCIFS.CMDSRC
QSHSRCIFS.CMD: PGM = QSHSRCIFSC
QSHSRCIFS.CMD: TEXT = Copy Source Mbr to IFS File
